import { DashboardLogic } from "../globals.slint";
import { Theme } from "../theme.slint";

component RepoSidebarItem inherits Rectangle {
    in property <string> text;
    in property <bool> active;
    callback clicked <=> touch.clicked;

    height: 40px;
    background: active ? Theme.surface : transparent;
    border-radius: 4px;

    touch := TouchArea {}

    HorizontalLayout {
        padding-left: 15px;
        spacing: 12px;
        Text { text: active ? "▶" : "📁"; vertical-alignment: center; color: active ? Theme.primary : Theme.text-muted; }
        Text {
            text: root.text;
            color: active ? Theme.text : Theme.text-muted;
            vertical-alignment: center;
            font-weight: active ? 700 : 400;
        }
    }
}

export component Sidebar inherits Rectangle {
    width: 250px;
    background: Theme.surface;

    Rectangle {
        x: parent.width - 1px;
        width: 1px;
        height: parent.height;
        background: Theme.border;
    }

    VerticalLayout {
        padding: 15px;
        spacing: 10px;
        Text {
            text: "REPOSITORIES";
            font-size: 12px;
            color: Theme.text-muted;
            font-weight: 800;
        }
        Rectangle { height: 10px; }
        for repo[i] in DashboardLogic.repositories: RepoSidebarItem {
            text: repo.name;
            active: DashboardLogic.active_repo_index == i && DashboardLogic.has_selected_repo;
            clicked => { DashboardLogic.select_repo(i) }
        }
        Rectangle {} // Spacer
    }
}
